### ISSUE TITLE
Vault PODS are in pending state for ever

### ISSUE THREAD

**Issue by ravismd** [kelseyhightower/vault-on-google-kubernetes-engine#21]
Hi, my vault pods are in pending state for ever after helm install "HA mode, as integrated storage"
ubuntu@ip-172-31-12-183:~$ kubectl get pods --selector='app.kubernetes.io/name=vault' --namespace='vault'
NAME      READY   STATUS    RESTARTS   AGE
vault-0   0/1     Pending   0          20m
vault-1   0/1     Pending   0          20m

could anyone please help me out to get rid of this error?

**Comment by sethvargo** [comment]
Hi @ravismd - this repo does not use helm, so I think you may have opened an issue on the wrong repo. Check out https://github.com/hashicorp/vault-helm instead. Thanks!
