### ISSUE TITLE
Support for a version that just uses a tainted node pool

### ISSUE THREAD

**Issue by andrewwatson** [kelseyhightower/vault-on-google-kubernetes-engine#3]
I'd like to submit a PR that shows setting up a tainted node pool so that the whole cluster doesn't have the vault service account on each node.

**Comment by sethvargo** [comment]
While I think that'd be accepted, the general "best practice" [we've been recommending](https://www.youtube.com/watch?v=B16YTeSs1hI) is to have a dedicated k8s cluster just for Vault.

**Comment by sethvargo** [comment]
I'm gonna close this, but we'd accept a PR for this 😄
