### ISSUE TITLE
[Question] - How to enable audit devices to stdout and save in Stackdriver Logs?

### ISSUE THREAD

**Issue by samuelbaruffi** [kelseyhightower/vault-on-google-kubernetes-engine#9]
Hello,
First of all, thanks for the awesome tutorial. It is very handy.

We have implemented this in our production cluster and were having issues getting the audit device logs to Stackdriver logs.

I have enabled the audit device to stdout by doing the following:

`vault audit enable file file_path=stdout`

Which I can confirm that is outputting to stdout on the vault container, if I check the logs with:

`kubectl logs vault-0 -f vault`

But unfortunately those logs are not being saved in Stackdriver for some reason, and I was not able to find more info on how to enable or troubleshoot it. See picture below for my stackdriver log on the vault container:

![screen shot 2018-10-11 at 2 17 54 pm](https://user-images.githubusercontent.com/7096709/46834536-819e7480-cd60-11e8-8305-f1a8ddc63d46.png)

Thanks in advance for the help.

Sam.

**Comment by samuelbaruffi** [comment]
Thanks for the quick reply @sethvargo .

See the full screenshot below (hiding few fields for security reasons):

![screen shot 2018-10-11 at 2 29 24 pm](https://user-images.githubusercontent.com/7096709/46835158-3a18e800-cd62-11e8-9537-7323cb9841d0.png)

The logs for the `vault-init` containers are being saved to Stackdriver, but for the `vault` container it does not seem they are. See screenshot below fir the `vault-init` container in the pod that is working on Stackdriver:

![screen shot 2018-10-11 at 2 35 16 pm](https://user-images.githubusercontent.com/7096709/46835424-fe325280-cd62-11e8-8149-48370deae6d3.png)

If I run `kubectl logs vault-0 -f vault` I'm able to see all the audit logs. 

Thanks for the help!

**Comment by sethvargo** [comment]
Hmm - that's really weird, since they are deployed the same. Are you able to reproduce it on a new cluster?

**Comment by samuelbaruffi** [comment]
I'd have to try creating a new cluster and building Vault again.

I'll post the results once I am able to replicate the environment in a new cluster.

Let me know if you find anything meanwhile.

Thank you.

**Comment by sethvargo** [comment]
I'm not able to reproduce it on my end. If you're familiar with Terraform, github.com/sethvargo/vault-on-gke is a one-command version of this same thing.

**Comment by samuelbaruffi** [comment]
Thank you @sethvargo,

I'll try to use the Terrraform script for my testing.

For now I'll go ahead and close this ticket.

Sam.

**Comment by MaxDiOrio** [comment]
I'm seeing the same thing with the Terraform script.  Absolutely 0 Kubernetes logs in Stackdriver.  But viewing kubectl logs for the Vault container shows the audit logs properly.

For a cluster created "manually" through the GCloud UI, you can see the K8S logs:
![image](https://user-images.githubusercontent.com/25855524/48010787-46d3f600-e0ec-11e8-8c01-4d85e1eb9c2f.png)

For the Vault cluster created through the Terraform, nothing.  
![image](https://user-images.githubusercontent.com/25855524/48010842-6539f180-e0ec-11e8-9691-68de2d8ef149.png)
